services:
  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4444:4444" # Porta do Selenium Grid
    dns:
      - 8.8.8.8
    network_mode: "host"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      selenium:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    volumes:
      - ./files:/files
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    dns:
      - 8.8.8.8
    network_mode: "host"

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fer67na
      PGDATA: /var/lib/postgresql/data
      DB_HOST: 127.0.0.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ] # , "-d", "logsis"]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 120s
    restart: always